name: Docker CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build Docker image and run tests
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/ci-cd-with-github        

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag ${{ steps.meta.outputs.tags }}

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        pip install -U pip pytest
        test -f requirements.txt && pip install -r requirements.txt

    - name: Install ChromeDriver
      run: |
        CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`
        wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip -d /home/runner/work/_temp
        sudo mv /home/runner/work/_temp/chromedriver /usr/local/bin/chromedriver
        sudo chown root:root /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Start Docker container
      run: |
        docker run -d --name test-container ${{ steps.meta.outputs.tags }}

    - name: Run unit tests
      run: |
        docker exec test-container python -m unittest test-unit-app.py

    - name: Run integration tests
      run: |
        docker exec test-container python test-integration-app.py

    - name: Push Docker image
      run: docker push ${{ steps.meta.outputs.tags }}